# Change these first
owner: glashtin # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Kith's Creations
    url: https://kithcreations.com
  - name: Gennings Lawn
    url: https://www.genningslawn.com
  - name: I Scoop for You
    url: https://iscoopforyou.com
  - name: I Scoop 4 You
    url: https://iscoop4you.com
  - name: M3 ToolBox
    url: https://m3toolbox.com
  - name: Lifeway One Source
    url: https://prospectservice.lifewaystores.com
  - name: PMC
    url: https://order.tpmco.com
  - name: Lexinet Prints
    url: https://lexinetprints.com
  - name: Agent Z Marketing
    url: https://www.agentzmarketing.com
  - name: ASR Nuxt
    url: https://lexasr.netlify.app
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://avatars.githubusercontent.com/u/6536683?v=4
  theme: night
  name: Site Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /uptime
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
